/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#f3e6d6",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#271900",
        "surface-container-lowest": "#ffffff",
        "surface": "#F6EFE6",
        "primary-fixed": "#ffdea5",
        "primary-fixed-dim": "#febb14",
        "outline": "#827560",
        "tertiary-fixed-dim": "#fcbc24",
        "primary": "#7b5800",
        "surface-tint": "#7b5800",
        "surface-container-highest": "#ede1d1",
        "inverse-primary": "#febb14",
        "inverse-surface": "#362f25",
        "secondary": "#755b00",
        "tertiary-fixed": "#ffdea5",
        "on-surface-variant": "#475569",
        "primary-container": "#f5b300",
        "secondary-container": "#fed669",
        "on-tertiary-fixed": "#261900",
        "on-secondary-container": "#765c00",
        "on-secondary-fixed": "#241a00",
        "error-container": "#ffdad6",
        "surface-container-low": "#fef2e1",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#5d4200",
        "secondary-fixed-dim": "#e9c258",
        "on-surface": "#0F172A",
        "on-background": "#0F172A",
        "outline-variant": "#d4c4ac",
        "tertiary-container": "#f4b419",
        "on-primary": "#ffffff",
        "tertiary": "#7b5800",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#654800",
        "surface-bright": "#fff8f3",
        "on-error": "#ffffff",
        "surface-container": "#f9ecdc",
        "on-tertiary-container": "#654800",
        "on-secondary-fixed-variant": "#584400",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdf90",
        "inverse-on-surface": "#fcefde",
        "surface-dim": "#e4d8c8",
        "on-tertiary-fixed-variant": "#5d4200",
        "surface-variant": "#ede1d1",
        "background": "#F6EFE6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "32px",
        "container-max": "1440px",
        "xs": "8px",
        "base": "4px",
        "sm": "16px",
        "md": "24px",
        "xl": "48px",
        "gutter": "24px",
        "container-padding": "40px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      "fontFamily": {
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}]
      }
    },
  },
  safelist: [
    {
      pattern: /(bg|text|border|ring)-(primary|secondary|tertiary|error|surface)(-[a-z]+)?(\/\d+)?/,
      variants: ['hover', 'focus', 'active', 'group-hover'],
    },
  ],
  plugins: [],
}
